version: '3.8'

services:
    django:
      build: .
      container_name: urlshortener
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - 8000:8000
      volumes:
        - .:/usr/src/app/
      env_file:
      - ./.env.dev
      depends_on:
        - redis
    db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev
    
    redis: 
      image: "redis:alpine"
    
      volumes:
        - .:/usr/src/app/
      depends_on:
        - django
        - redis
volumes:
  postgres_data:
