version: '3.8'

services:
    django:
      build: .
      container_name: urlshortener
      command: 
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
      ports:
        - 8000:8000
      volumes:
        - .:/usr/src/app/
      env_file:
        - ./.env.dev
    nginx:
      build: ./nginx
      ports:
        - 1337:80
      volumes:
        - static_volume:/usr/src/app/staticfiles
      depends_on:
        - django
    db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev
    
volumes:
  postgres_data:
  static_volume:
