version: '3.8'

services:
    web:
      build: .
      container_name: web
      ports:
        - 8000:8000
      volumes:
        - .:/usr/src/app/
      env_file:
        - ./.env.dev
      command: gunicorn ornekproje.wsgi:application --bind 0.0.0.0:8000
    nginx:
      build: ./nginx
      ports:
        - 1337:80
      volumes:
        - static_volume:/usr/src/app/staticfiles
      depends_on:
        - web
    db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev
    
volumes:
  postgres_data:
  static_volume:
