# Generated by Django 4.2.3 on 2023-07-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0002_kategoriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kurslar.kategoriler'),
        ),
    ]
