# Generated by Django 4.2.3 on 2023-07-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0003_kurs_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='slug',
            field=models.SlugField(max_length=15, unique=True),
        ),
    ]
