# Generated by Django 4.2.3 on 2023-07-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0006_alter_kurs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='kategori',
            field=models.ManyToManyField(blank=True, to='kurslar.kategoriler'),
        ),
    ]
