# Generated by Django 4.2.3 on 2023-07-28 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0009_alter_kurs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 11, 2, 49, 329025)),
        ),
    ]
