# Generated by Django 4.2.3 on 2023-08-01 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0011_uploadmodel_alter_kurs_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='kurs',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 1, 13, 15, 56, 543124)),
        ),
    ]
