# Generated by Django 4.2.3 on 2023-08-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0012_delete_uploadmodel_remove_kurs_imageurl_kurs_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 1, 13, 27, 21, 551753)),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
