# Generated by Django 4.2.3 on 2023-08-02 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0013_alter_kurs_date_alter_kurs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 11, 30, 52, 904039)),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
