# Generated by Django 4.2.3 on 2023-08-02 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0014_alter_kurs_date_alter_kurs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 15, 7, 47, 396137)),
        ),
    ]
