# Generated by Django 4.2.3 on 2023-08-03 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0017_alter_kurs_date_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 9, 22, 23, 596372)),
        ),
    ]
